*****************************************************************************
*        ACTUALIZADOR DE TABLA DE FACTORES                                  *
*****************************************************************************
PUSH KEY CLEAR
ON KEY LABEL F1 DO PROCIMP

SELECT 1
USE IPNFACTO INDEX IPNFACTO ALIAS TABLA
store "FACTORES DE PAGO" TO HEADING
store .t. to fact
do while fact
   set color to W+/B
   @ 5,0 clear to 21,79
   @ 5,0 to 21,79 double
   @ 5,40-(LEN(HEADING)/2) SAY HEADING
   @ 06,2   SAY "CODIGO DE FACTOR :"
   @ 07,2   SAY "DIAS ORDINARIOS  :"
   @ 08,2   SAY "DIAS DE DESCANSO :"
   @ 09,2   SAY "HRS.x DIA. D,M,N :"
   @ 10,2   SAY "SOBRE TIEMPO A,B :"
   @ 11,2   SAY "TIEMPO VIAJE A,B :"
   @ 12,2   SAY "DESCANSO CONTRAC.:"
   @ 13,2   SAY "DESCANSO LEGAL   :"
   @ 14,2   SAY "DESCANSO COMPEN. :"
   @ 15,2   SAY "B.N. TRAB, VIAJE :"
   @ 16,2   SAY "COMIDA, REP/COM. :"
   @ 17,2   SAY "AYUDA, VIVIENDA  :"
   @ 18,2   SAY "FERIADO ORDINARIO:"
   @ 19,2   SAY "PRIMA DOM./FER.  :"
   @ 20,2   SAY "CESTA BASICA     :"
   STORE SPACE(5) TO WFACTOR
   STORE "INGRESE EL CODIGO DE LOS FACTORES. F1=VER, <ENTER>=SALIR" TO MES
   DO MENSAJE WITH MES
   @ 6,20 GET WFACTOR
   READ
   IF WFACTOR = SPACE(5)
      POP KEY
      SET COLOR TO
      CLOSE DATA
      CLOSE INDEX
      RETURN
   ENDIF
   FIND &WFACTOR
   IF EOF()
      STORE "CODIGO NO REGISTRADO, DESEA INGRESAR ? (S/N)" TO MESS
      STORE "S" TO P1
      STORE "N" TO P2
      STORE " " TO RESP
      DO PIDE2 WITH P1,P2,MESS,RESP
      IF RESP <> "S"
         LOOP
      ENDIF

     *********   INGRESO DE NUEVOS FACTOES     **************
      APPEND BLANK
      REPLACE FACCOD WITH WFACTOR

      STORE "INGRESE LA DESCRIPCION DE LOS FACTORES" TO MES
      DO MENSAJE WITH MES
      @ 06,40 GET DESCRI
      READ

      STORE "INGRESE EL PROMEDIO DE DIAS A TRABAJAR POR PERIODO" TO MES
      DO MENSAJE WITH MES
      @ 07,20 GET F_DIAS PICTURE "##.##"
      READ

      STORE "INGRESE EL PROMEDIO DE DIAS A PAGAR POR DESCANSO NORMAL" TO MES
      DO MENSAJE WITH MES
      @ 08,20 GET F_DESNOR PICTURE "##.##"
      READ

      STORE "INGRESE EL PROMEDIO DE HORAS A TRABAJAR POR DIA" TO MES
      DO MENSAJE WITH MES
      @ 09,20 GET F_HORASD PICTURE "##.##"
      @ 09,26 GET F_HORASM PICTURE "##.##"
      @ 09,32 GET F_HORASN PICTURE "##.##"
      READ

      STORE "INGRESE EL % DEL PRECIO POR HORA A PAGAR POR SOBRE TIEMPO" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WSTA
      STORE 0 TO WSTB
      @ 10,20 GET WSTA PICTURE "####.##"
      @ 10,28 GET WSTB PICTURE "####.##"
      READ
      STORE WSTA/100 TO WSTA
      REPLACE F_STA WITH WSTA
      STORE WSTB/100 TO WSTB
      REPLACE F_STB WITH WSTB

      STORE "% DEL SUELDO/Hrs.A PAGAR POR TIEMPO DE VIAJE DE 1.5 Hrs. y +1.5 Hrs." TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WTVA
      STORE 0 TO WTVB
      @ 11,20 GET WTVA PICTURE "####.##"
      @ 11,28 GET WTVB PICTURE "####.##"
      READ
      STORE WTVA/100 TO WTVA
      REPLACE F_TVA WITH WTVA
      STORE WTVB/100 TO WTVB
      REPLACE F_TVB WITH WTVB

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR DESCANSO CONTRACTUAL TRABAJADO" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WDCON
      @ 12,20 GET WDCON PICTURE "####.##"
      READ
      STORE WDCON/100 TO WDCON
      REPLACE F_DESCON WITH WDCON

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR DESCANSO LEGAL TRABAJADO" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WDLEG
      @ 13,20 GET WDLEG PICTURE "####.##"
      READ
      STORE WDLEG/100 TO WDLEG
      REPLACE F_DESLEG WITH WDLEG

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR DESCANSO COMPENSATORIO TRABAJADO" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WDCOM
      @ 14,20 GET WDCOM PICTURE "####.##"
      READ
      STORE WDCOM/100 TO WDCOM
      REPLACE F_DESCOM WITH WDCOM

      STORE "% DEL SUELDO/Hrs.A PAGAR POR BONO NOCTURNO TRABAJADO Y DE VIAJE" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WBNT
      STORE 0 TO WBNV
      @ 15,20 GET WBNT PICTURE "####.##"
      @ 15,28 GET WBNV PICTURE "####.##"
      READ
      STORE WBNT/100 TO WBNT
      REPLACE F_BNOCTU  WITH WBNT
      STORE WBNV/100 TO WBNV
      REPLACE F_BNVIAJE WITH WBNV

      STORE "INGRESE EL MONTO EN BS. A PAGAR POR COMIDA Y FACTOR DE REPOSO-COMIDA" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WREPCOM
      @ 16,20 GET F_COMIDA  PICTURE "#####.##"
      @ 16,30 GET WREPCOM   PICTURE "####.##"
      READ
      STORE WREPCOM/100  TO WREPCOM
      REPLACE F_REPCOM WITH WREPCOM

      STORE "INGRESE EL MONTO EN BS. A PAGAR POR AYUDA DE CIUDAD Y VIVIENDA" TO MES
      DO MENSAJE WITH MES
      @ 17,20 GET F_AYUCIU  PICTURE "#####.##"
      @ 17,30 GET F_VIVIEN  PICTURE "#####.##"
      READ

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR FERIADO" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WFO
      @ 18,20 GET WFO PICTURE "####.##"
      READ
      STORE WFO/100 TO WFO
      REPLACE F_FO WITH WFO

      STORE "INGRESE EL % DEL SUELDO POR DIA A PAGAR POR BONO DOMINICAL O PRIMA POR FERIADO" TO MES
      DO MENSAJE WITH MES
      STORE 0 TO WBD
      @ 19,20 GET WBD  PICTURE "####.##"
      READ
      STORE WBD/100 TO WBD
      REPLACE F_BDOMIN WITH WBD

      STORE "INGRESE EL MONTO MENSUAL A PAGAR POR CESTA BASICA" TO MES
      DO MENSAJE WITH MES
      @ 20,20 GET F_CESTA PICTURE "######.##"
      READ

      LOOP
   ENDIF

   ******  MODIFICAR  FACTORES EXISTENTES  **************
      @ 06,40 SAY DESCRI
      @ 07,20 SAY F_DIAS              PICTURE "##.##"
      @ 08,20 SAY F_DESNOR            PICTURE "##.##"
      @ 09,20 SAY F_HORASD            PICTURE "##.##"
      @ 09,26 SAY F_HORASM            PICTURE "##.##"
      @ 09,32 SAY F_HORASN            PICTURE "##.##"
      @ 10,20 SAY F_STA*100           PICTURE "####.##"
      @ 10,28 SAY F_STB*100           PICTURE "####.##"
      @ 11,20 SAY F_TVA*100           PICTURE "####.##"
      @ 11,28 SAY F_TVB*100           PICTURE "####.##"
      @ 12,20 SAY F_DESCON*100        PICTURE "####.##"
      @ 13,20 SAY F_DESLEG*100        PICTURE "####.##"
      @ 14,20 SAY F_DESCOM*100        PICTURE "####.##"
      @ 15,20 SAY F_BNOCTU*100        PICTURE "####.##"
      @ 15,28 SAY F_BNVIAJE*100       PICTURE "####.##"
      @ 16,20 SAY F_COMIDA            PICTURE "#####.##"
      @ 16,30 SAY F_REPCOM*100        PICTURE "####.##"
      @ 17,20 SAY F_AYUCIU            PICTURE "#####.##"
      @ 17,30 SAY F_VIVIEN            PICTURE "#####.##"
      @ 18,20 SAY F_FO*100            PICTURE "####.##"
      @ 19,20 SAY F_BDOMIN*100        PICTURE "####.##"
      @ 20,20 SAY F_CESTA             PICTURE "######.##"

      STORE "OPCIONES: (M)ODIFICAR, (E)LIMINAR, (S)ALIR" to mess
      store "M" TO P1
      STORE "E" TO P2
      STORE "S" TO P3
      STORE " " TO RESP
      DO PIDE3 WITH P1, P2, P3, MESS, RESP

      IF RESP = "E"
         SELECT 2
         USE IPNOMINA ALIAS NOMINAS
         LOCATE FOR FACTCOD = WFACTOR
         IF FOUND()
            STORE "ERROR, la nomina "+rtrim(nominas->desnom)+" esta sujeta a esta tabla" to mes
            do aviso with mes
            SELECT 1
         else
            select 1
            DELETE
            PACK
         endif
         LOOP
      ENDIF

      IF RESP = "S"
         LOOP
      ENDIF

      IF RESP = "M"

      STORE "INGRESE LA DESCRIPCION DE LOS FACTORES" TO MES
      DO MENSAJE WITH MES
      @ 06,40 GET DESCRI
      READ
      
      STORE "INGRESE EL PROMEDIO DE DIAS A TRABAJAR POR PERIODO" TO MES
      DO MENSAJE WITH MES
      @ 07,20 GET F_DIAS PICTURE "##.##"
      READ

      STORE "INGRESE EL PROMEDIO DE DIAS A PAGAR POR DESCANSO NORMAL" TO MES
      DO MENSAJE WITH MES
      @ 08,20 GET F_DESNOR PICTURE "##.##"
      READ

      STORE "INGRESE EL PROMEDIO DE HORAS A TRABAJAR POR DIA" TO MES
      DO MENSAJE WITH MES
      @ 09,20 GET F_HORASD PICTURE "##.##"
      @ 09,26 GET F_HORASM PICTURE "##.##"
      @ 09,32 GET F_HORASN PICTURE "##.##"
      READ

      STORE "INGRESE EL % DEL PRECIO POR HORA A PAGAR POR SOBRE TIEMPO" TO MES
      DO MENSAJE WITH MES
      STORE F_STA*100 TO WSTA
      STORE F_STB*100 TO WSTB
      @ 10,20 GET WSTA PICTURE "####.##"
      @ 10,28 GET WSTB PICTURE "####.##"
      READ
      STORE WSTA/100 TO WSTA
      REPLACE F_STA WITH WSTA
      STORE WSTB/100 TO WSTB
      REPLACE F_STB WITH WSTB

      STORE "% DEL SUELDO/Hrs.A PAGAR POR TIEMPO DE VIAJE DE 1.5 Hrs. y +1.5 Hrs." TO MES
      DO MENSAJE WITH MES
      STORE F_TVA*100 TO WTVA
      STORE F_TVB*100 TO WTVB
      @ 11,20 GET WTVA PICTURE "####.##"
      @ 11,28 GET WTVB PICTURE "####.##"
      READ
      STORE WTVA/100 TO WTVA
      REPLACE F_TVA WITH WTVA
      STORE WTVB/100 TO WTVB
      REPLACE F_TVB WITH WTVB

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR DESCANSO CONTRACTUAL TRABAJADO" TO MES
      DO MENSAJE WITH MES
      STORE F_DESCON*100 TO WDCON
      @ 12,20 GET WDCON PICTURE "####.##"
      READ
      STORE WDCON/100 TO WDCON
      REPLACE F_DESCON WITH WDCON

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR DESCANSO LEGAL TRABAJADO" TO MES
      DO MENSAJE WITH MES
      STORE F_DESLEG*100 TO WDLEG
      @ 13,20 GET WDLEG PICTURE "####.##"
      READ
      STORE WDLEG/100 TO WDLEG
      REPLACE F_DESLEG WITH WDLEG

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR DESCANSO COMPENSATORIO TRABAJADO" TO MES
      DO MENSAJE WITH MES
      STORE F_DESCOM*100 TO WDCOM
      @ 14,20 GET WDCOM PICTURE "####.##"
      READ
      STORE WDCOM/100 TO WDCOM
      REPLACE F_DESCOM WITH WDCOM

      STORE "% DEL SUELDO/Hrs.A PAGAR POR BONO NOCTURNO TRABAJADO Y DE VIAJE" TO MES
      DO MENSAJE WITH MES
      STORE F_BNOCTU*100  TO WBNT
      STORE F_BNVIAJE*100 TO WBNV
      @ 15,20 GET WBNT PICTURE "####.##"
      @ 15,28 GET WBNV PICTURE "####.##"
      READ
      STORE WBNT/100 TO WBNT
      REPLACE F_BNOCTU  WITH WBNT
      STORE WBNV/100 TO WBNV
      REPLACE F_BNVIAJE WITH WBNV

      STORE "INGRESE EL MONTO EN BS. A PAGAR POR COMIDA Y FACTOR DE REPOSO-COMIDA" TO MES
      DO MENSAJE WITH MES
      STORE F_REPCOM*100 TO WREPCOM
      @ 16,20 GET F_COMIDA  PICTURE "#####.##"
      @ 16,30 GET WREPCOM   PICTURE "####.##"
      READ
      STORE WREPCOM/100  TO WREPCOM
      REPLACE F_REPCOM WITH WREPCOM

      STORE "INGRESE EL MONTO EN BS. A PAGAR POR AYUDA DE CIUDAD Y VIVIENDA" TO MES
      DO MENSAJE WITH MES
      @ 17,20 GET F_AYUCIU  PICTURE "#####.##"
      @ 17,30 GET F_VIVIEN  PICTURE "#####.##"
      READ

      STORE "INGRESE EL % DEL SUELDO DIARIO A PAGAR POR FERIADO" TO MES
      DO MENSAJE WITH MES
      STORE F_FO*100 TO WFO
      @ 18,20 GET WFO PICTURE "####.##"
      READ
      STORE WFO/100 TO WFO
      REPLACE F_FO WITH WFO

      STORE "INGRESE EL % DEL SUELDO POR DIA A PAGAR POR BONO DOMINICAL O PRIMA POR FERIADO" TO MES
      DO MENSAJE WITH MES
      STORE F_BDOMIN*100 TO WBD
      @ 19,20 GET WBD  PICTURE "####.##"
      READ
      STORE WBD/100 TO WBD
      REPLACE F_BDOMIN WITH WBD

      STORE "INGRESE EL MONTO MENSUAL A PAGAR POR CESTA BASICA" TO MES
      DO MENSAJE WITH MES
      @ 20,20 GET F_CESTA PICTURE "######.##"
      READ
      LOOP
   ENDIF
enddo
RETURN
************
PROC PROCIMP
************
SAVE SCRE TO WSCREIMP
STORE "OPCIONES: (M)ONITOR, (I)MPRESORA, (S)ALIR" to mess
store "M" TO P1
STORE "I" TO P2
STORE "S" TO P3
STORE " " TO RESP
DO PIDE3 WITH P1, P2, P3, MESS, RESP
STORE "" TO WSALIDA
IF RESP = "M"
   STORE 20  TO WSALTO
   STORE "M" TO WSALIDA
   SET DEVI  TO SCRE
ELSE
   IF RESP = "I"
      STORE 55  TO WSALTO
      STORE "I" TO WSALIDA
      SET DEVI  TO PRINT
   ENDIF
ENDIF
*
IF RESP<>"S"
   STORE 100 TO WLINE
   STORE 0   TO WPAGE
   GO TOP
   DO WHILE .NOT. EOF()
      STORE WLINE+1 TO WLINE
      IF WLINE>=WSALTO
         DO HEADER
      ENDIF
      @ WLINE,00 SAY FACCOD
      @ WLINE,40 SAY DESCRI
      SKIP
   ENDDO
ENDIF
IF WSALIDA="M"
   STORE "OPRIMA <ENTER> PARA FINALIZAR" TO MES
   DO AVISO WITH MES
ELSE
   IF WSALIDA = "I"
      EJECT
   ENDIF
ENDIF
SET DEVI TO SCRE
REST SCRE FROM WSCREIMP
RETURN
************
PROC HEADER
************
STORE WPAGE+1 TO WPAGE
IF WSALIDA="M"
   IF WPAGE>1
      STORE "OPRIMA <ENTER> PARA CONTINUAR" TO MES
      DO AVISO WITH MES
   ENDIF
   @ 0,0 CLEAR
ENDIF
IF LASTKEY()=27
   GO BOTT
ENDIF
@ 00,00 SAY QQWW
@ 00,60 SAY "FECHA  : "+DTOC(DATE())
@ 01,00 SAY "SISTEMA DE NOMINA"
@ 01,60 SAY "PAGINA : "+STR(WPAGE,2)
@ 02,00 SAY "LISTADO DE FACTORES DE PAGO"
@ 04,00 SAY "CODIGO"
@ 04,40 SAY "DESCRIPCION"
@ 05,00 SAY "------"
@ 05,40 SAY "----------------------------"
STORE 06 TO WLINE
RETURN

